nicer error messages in fakecamera; let it take a screen number as an argument
and one or two minor changes recommended by shellcheck.

diff --git a/fakecamera b/fakecamera
--- a/fakecamera
+++ b/fakecamera
@@ -4,14 +4,30 @@
 sudo rmmod v4l2loopback 2> /dev/null
 sudo modprobe v4l2loopback video_nr=7 'card_label=myFakeCam'
 
-xrandr --listactivemonitors
-read -p "Which monitor you want to share: " MON_NUMBER
+input=$1
+if [[ -z ${input} ]]; then
+    xrandr --listactivemonitors
+    read -erp "Which monitor you want to share: " -i 0 MON_NUMBER
 
-MON_PARSE=`xrandr --listactivemonitors | grep "$MON_NUMBER:" | cut -f4 -d' '`
-MON_HEIGHT=`echo $MON_PARSE | cut -f2 -d'/' | cut -f2 -d'x'`
-MON_WIDTH=`echo $MON_PARSE | cut -f1 -d'/'`
-MON_X=`echo $MON_PARSE | cut -f2 -d'+'`
-MON_Y=`echo $MON_PARSE | cut -f3 -d'+'`
+    if [[ -z ${MON_NUMBER} ]]; then
+        echo "you must enter something; try again"
+        exit 2
+    fi
+else
+    MON_NUMBER=${input}
+fi
+
+MON_PARSE=$(xrandr --listactivemonitors | grep "$MON_NUMBER:" | cut -f4 -d' ')
+
+if [[ -z ${MON_PARSE} ]]; then
+    echo "monitor '${MON_NUMBER}' not found"
+    exit 1
+fi
+
+MON_HEIGHT=$(echo "$MON_PARSE" | cut -f2 -d'/' | cut -f2 -d'x')
+MON_WIDTH=$(echo "$MON_PARSE" | cut -f1 -d'/')
+MON_X=$(echo "$MON_PARSE" | cut -f2 -d'+')
+MON_Y=$(echo "$MON_PARSE" | cut -f3 -d'+')
 geom="${DISPLAY}+${MON_X},${MON_Y}"
 dim="${MON_WIDTH}x${MON_HEIGHT}"
 
